#services:
#
#  web:
#    build:
#      context: .
#
#    env_file:
#      - ./.env
#
#    ports:
#      - "5000:5000"
#    volumes:
#      - your-volume-name:/app/data
#
#    depends_on:
#      - db
#
#  db:
#    image: postgres:latest
#
#    restart: always
#    container_name: postgres
#    volumes:
#      - postgres_volume:/var/lib/postgresql/data/
#
#    env_file:
#      - ./.env
#    ports:
#      - "5431-5432"
#
##  redis:
##    image: redis:latest
##
##    restart: always
##    ports:
##      - "6380:6379"
#
#
#
#volumes:
#  postgres_volume:
#  your-volume-name:


version: '3.8'

services:

  web:
    build:
      context: .

    env_file:
      - .env

#    command: ["/flask_app/Docker/app.sh"]

    ports:
      - "5000:5000"
    volumes:
      - your-volume-name:/app/data

    networks:
      - my_network

    depends_on:
      - db

  db:
    image: postgres:latest

    restart: always
    container_name: db_app
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

    env_file:
      - .env
    ports:
      - "5431:5432"

    networks:
      - my_network



volumes:
  postgres_volume:
  your-volume-name:


networks:  # Определяем сеть
  my_network:
